# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            shell: bash
            binary: linux
            arch: amd64

         # https://github.com/actions/partner-runner-images
          - os: ubuntu-24.04-arm
            shell: bash
            binary: linux
            arch: arm64

          # needs a paid plan            
          # - os: macos-latest-large
          #   shell: bash
          #   binary: macos
          #   arch: amd64

          - os: macos-latest
            shell: bash
            binary: macos
            arch: aarch64

          - os: windows-latest
            shell: pwsh
            binary: windows
            arch: amd64

          # not working on GitHub ACitons  but on real machine
          # - os: windows-latest
          #   shell: pwsh
          #   binary: windows
          #   arch: aarch64
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Output OS and Architecture
      shell: pwsh
      run: |
        ./.github/workflows/os-info.ps1 -Title "Tests run on" -MatrixOS "${{ matrix.os }}" -MatrixShell "${{ matrix.shell }}" -MatrixBinary "${{ matrix.binary }}" -MatrixArch "${{ matrix.arch }}"

    - name: Test
      run: go test -v ./...

  build:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: ./build.ps1
    
    - name: Upload binary Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: goplayground-binaries
        path: bin/**/*
        retention-days: 5

  run-binary:
    name: Run binary on ${{ matrix.os }}-${{ matrix.arch }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            shell: bash
            binary: linux
            arch: amd64

          # https://github.com/actions/partner-runner-images
          - os: ubuntu-24.04-arm
            shell: bash
            binary: linux
            arch: arm64

          # needs a paid plan            
          # - os: macos-latest-large
          #   shell: bash
          #   binary: macos
          #   arch: amd64

          - os: macos-latest
            shell: bash
            binary: macos
            arch: aarch64

          - os: windows-latest
            shell: pwsh
            binary: windows
            arch: amd64

          # not working on GitHub ACitons  but on real machine
          # - os: windows-latest
          #   shell: pwsh
          #   binary: windows
          #   arch: aarch64 

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - uses: actions/checkout@v4

    - name: Download binary artifacts
      uses: actions/download-artifact@v4
      with:
        name: goplayground-binaries
        path: bin

    - name: Output OS and Architecture
      shell: pwsh
      run: |
        ./.github/workflows/os-info.ps1 -Title "Software run on" -MatrixOS "${{ matrix.os }}" -MatrixShell "${{ matrix.shell }}" -MatrixBinary "${{ matrix.binary }}" -MatrixArch "${{ matrix.arch }}"

    - name: List artifacts directory
      run: ls -r bin

    - name: Run binary with -store option
      if: matrix.os != 'windows-latest'
      run: |
        # make binary executable
        chmod +x bin/goplayground-${{ matrix.binary }}-${{ matrix.arch }}
        # Create data directory for database
        mkdir -p data
        # Store command for reuse
        echo "COMMAND=./bin/goplayground-${{ matrix.binary }}-${{ matrix.arch }} -contract-file ./bin/config/contract.json -store" >> $GITHUB_ENV
    
    - name: Run binary with -store option
      if: matrix.os == 'windows-latest'
      run: |
        # Create data directory for database
        mkdir -p data
        # Store command for reuse
        Write-Output "COMMAND=./bin/goplayground-${{ matrix.binary }}-${{ matrix.arch }}.exe -contract-file ./bin/config/contract.json -store" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Execute and log command
      run: |
        echo "### Command executed:" >> $GITHUB_STEP_SUMMARY
        echo "```${{ matrix.shell }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ env.COMMAND }}" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "### Command output:" >> $GITHUB_STEP_SUMMARY
        echo "```${{ matrix.shell }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          $OUTPUT = & ${{ env.COMMAND }}
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
        else
          OUTPUT=$(${{ env.COMMAND }})
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
        fi
        echo "```" >> $GITHUB_STEP_SUMMARY
